"""``heightmap-prep-world``: MRS world file -> heightmap-prep world config.

Reads the safety area out of an MRS UAV system world file and writes the
heightmap-prep world configuration that covers it, so a site can go from
"where the vehicle is allowed to fly" to "which terrain to prepare" in one step::

    heightmap-prep-world worlds/world_bechovice.yaml -o examples/bechovice.yaml

The generated bounds are the WGS84 bounding box of the safety area polygon,
grown by a margin on every side; everything else uses the library defaults.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Sequence

from . import __version__
from .config import DEFAULT_SOURCE, Wgs84Bounds, load_world
from .errors import HeightmapPrepError
from .mrs_world import (
    DEFAULT_UTM_ZONE,
    MrsWorld,
    load_mrs_world,
    safety_area_bounds,
)

log = logging.getLogger("heightmap_prep.world")

LOG_LEVELS = {
    "debug": logging.DEBUG,
    "info": logging.INFO,
    "warning": logging.WARNING,
    "error": logging.ERROR,
}

#: Margin added around the safety area, in metres.
DEFAULT_MARGIN_M = 5.0

#: Decimal places kept for degrees; 7 is about a centimetre.
COORD_DECIMALS = 7

EPILOG = """\
examples:
  heightmap-prep-world worlds/world_bechovice.yaml
  heightmap-prep-world worlds/world_bechovice.yaml -o examples/bechovice.yaml
  heightmap-prep-world worlds/*.yaml -o examples/ --margin-m 250

With no --output the configuration is printed to stdout.  With several inputs
--output must be a directory, and each world is written to <name>.yaml in it.

exit codes:
  0  success
  2  a world file could not be read or produced no usable safety area
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="heightmap-prep-world",
        description=(
            "Generate a heightmap-prep world configuration from the safety area "
            "of an MRS UAV system world file."
        ),
        epilog=EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "inputs",
        nargs="+",
        metavar="WORLD.yaml",
        help="one or more MRS world files",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        metavar="PATH",
        help="output file (single input) or directory (several inputs); "
        "defaults to stdout",
    )
    parser.add_argument(
        "--margin-m",
        type=float,
        default=DEFAULT_MARGIN_M,
        metavar="METRES",
        help=f"margin added around the safety area (default: {DEFAULT_MARGIN_M:g})",
    )
    parser.add_argument(
        "--name",
        metavar="NAME",
        help="name for the generated world; defaults to the input filename with "
        "any 'world_' prefix stripped",
    )
    parser.add_argument(
        "--resolution",
        type=float,
        default=2.0,
        metavar="FLOAT",
        help="heightmap resolution in metres written into the output (default: 2.0)",
    )
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE,
        metavar="ID",
        help=f"heightmap source written into the output (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument(
        "--utm-zone",
        default=DEFAULT_UTM_ZONE,
        metavar="ZONE",
        help="UTM zone to assume for worlds whose origin is UTM, since the files "
        f"do not record one (default: {DEFAULT_UTM_ZONE})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite an existing output file",
    )
    parser.add_argument(
        "--log-level",
        choices=sorted(LOG_LEVELS),
        default="info",
        help="logging verbosity (default: info)",
    )
    parser.add_argument(
        "--version", action="version", version=f"heightmap-prep {__version__}"
    )
    return parser


def render_world_config(
    world: MrsWorld,
    bounds: Wgs84Bounds,
    *,
    margin_m: float,
    resolution_m: float,
    source: str,
) -> str:
    """Render the heightmap-prep world configuration for ``world``."""
    west, south, east, north = (
        round(value, COORD_DECIMALS)
        for value in (bounds.west, bounds.south, bounds.east, bounds.north)
    )
    area = world.safety_area
    # repr() keeps the decimal point, so 2.0 does not become a YAML integer.
    resolution = repr(float(resolution_m))
    origin_note = (
        f", origin assumed to be UTM zone {world.utm_zone}"
        if world.units == "UTM"
        else ""
    )
    return f"""\
# Generated by heightmap-prep-world {__version__} from {world.path.name}.
# Bounds are the bounding box of the safety area ({len(area.points)} vertices,
# frame {area.frame_name}{origin_note}), grown by {margin_m:g} m on every side.
name: {world.name}

bounds:
  type: wgs84
  west: {west}
  south: {south}
  east: {east}
  north: {north}

heightmap:
  source: {source}
  resolution_m: {resolution}

rgb:
  enabled: false
"""


def _resolve_destination(
    output: Path | None, world: MrsWorld, many: bool
) -> Path | None:
    """Where one world's configuration should be written; ``None`` for stdout."""
    if output is None:
        return None
    if many or output.is_dir() or str(output).endswith(("/", "\\")):
        return output / f"{world.name}.yaml"
    return output


def convert(
    path: Path,
    *,
    margin_m: float,
    resolution_m: float,
    source: str,
    utm_zone: str,
    name: str | None = None,
) -> tuple[MrsWorld, Wgs84Bounds, str]:
    """Read one MRS world file and render its heightmap-prep configuration."""
    world = load_mrs_world(path, name=name, utm_zone=utm_zone)
    bounds = safety_area_bounds(world, margin_m)
    text = render_world_config(
        world, bounds, margin_m=margin_m, resolution_m=resolution_m, source=source
    )
    return world, bounds, text


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=LOG_LEVELS[args.log_level],
        format="%(levelname)-7s %(message)s",
        stream=sys.stderr,
    )

    inputs = [Path(p) for p in args.inputs]
    if args.name and len(inputs) > 1:
        parser.error("--name can only be used with a single input file")
    if args.margin_m < 0:
        parser.error("--margin-m must not be negative")
    if len(inputs) > 1 and args.output is not None and args.output.exists():
        if not args.output.is_dir():
            parser.error(
                f"--output must be a directory when several inputs are given: {args.output}"
            )

    many = len(inputs) > 1
    written: list[Path] = []
    documents: list[str] = []

    for path in inputs:
        try:
            world, bounds, text = convert(
                path,
                margin_m=args.margin_m,
                resolution_m=args.resolution,
                source=args.source,
                utm_zone=args.utm_zone,
                name=args.name,
            )
        except HeightmapPrepError as exc:
            log.error("%s", exc)
            return 2

        log.info(
            "%s: safety area %d vertices -> bounds %.6f, %.6f .. %.6f, %.6f (+%g m)",
            world.name,
            len(world.safety_area.points),
            bounds.west,
            bounds.south,
            bounds.east,
            bounds.north,
            args.margin_m,
        )

        destination = _resolve_destination(args.output, world, many)
        if destination is None:
            documents.append(text)
            continue

        if destination.exists() and not args.force:
            log.error("%s already exists; pass --force to overwrite it", destination)
            return 2
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8")

        # The output must be something heightmap-prep can actually consume.
        try:
            load_world(destination)
        except HeightmapPrepError as exc:  # pragma: no cover - guards a regression
            log.error("generated %s is not a valid world configuration: %s", destination, exc)
            return 2

        written.append(destination)
        log.info("wrote %s", destination)

    if documents:
        sys.stdout.write("---\n".join(documents))

    if written:
        log.info("generated %d world configuration(s)", len(written))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
